org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false
# Evita corrupção do cache incremental quando projeto e SDK estão em unidades diferentes no Windows.
kotlin.incremental=false
kotlin.compiler.execution.strategy=in-process
